registryProxy:
  tag:

proxy:
  remoteurl: https://registry-1.docker.io

store: filesystem # filesystem | s3
s3:
  region: ""
  bucket: ""
  endpoint: s3.amazonaws.com
  prefix: ""
  encrypted: true
  secure: true
  v4auth: true
  skipverify: false

secret:
  key:
  store:
    name: default
    kind: ClusterSecretStore

prometheus:
  enable: false
